---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'view-qubership-apihub-sniffer-agent'
subjects:
  - kind: ServiceAccount
    name: 'qubership-apihub-sniffer-agent'
    namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit


