apiVersion: v1
stringData:
  api_key: '{{ .Values.qubershipApihubSnifferAgent.env.snifferApiKey }}'
  internal_key: '{{ .Values.qubershipApihubSnifferAgent.env.snifferInternalKey }}'
kind: Secret
metadata:
  name: 'qubership-apihub-sniffer-agent-keys-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: 'qubership-apihub-sniffer-agent'
    app.kubernetes.io/managed-by: 'helm'

type: Opaque