apiVersion: v1
stringData:
    storage_server_username: '{{ .Values.qubershipApihubSnifferAgent.env.s3Storage.username }}'
    storage_server_password: '{{ .Values.qubershipApihubSnifferAgent.env.s3Storage.password }}'
    storage_server_crt: '{{ .Values.qubershipApihubSnifferAgent.env.s3Storage.crt }}'
kind: Secret
metadata:
    name: 'qubership-apihub-sniffer-agent-s3-secret'
    namespace: '{{ .Release.Namespace }}'
    labels:
        app.kubernetes.io/part-of: 'qubership-apihub-sniffer-agent'
        app.kubernetes.io/managed-by: 'helm'
type: Opaque