---
apiVersion: v1
kind: Secret
metadata:
    name: 'qubership-apihub-sniffer-agent-secret'
    namespace: '{{ .Release.Namespace }}'
    annotations:
        kubernetes.io/service-account.name: 'qubership-apihub-sniffer-agent'
type: kubernetes.io/service-account-token

