qubershipApihubSnifferAgent:
  version: ''
  image:
    repository: 'ghcr.io/netcracker/qubership-apihub-sniffer-agent' 
    tag: 'dev'
  # Section with resource limits
  # Mandatory
  # Below are the default values which are good enough for any cases including production
  resource:
    memory:
      request: "256Mi"
      limit: "256Mi"
    cpu:  
      request: "30m"
      limit: "1"
  env:
    logLevel: 'DEBUG'
    snifferApiKey: ''
    snifferInternalKey: ''
    cloudName: ''
    agentUrl: 'qubership-apihub-sniffer-agent.localtest.me'
    s3Storage:
      username: ''
      password: ''
#   public.crt | base64
      crt: ''
      url: 'minio.minio-tenant'
      bucketName: 'qubership-apihub-sniffer-s3-bucket'
      active: 'true'
  spec:
    nodeSelectorKey: ''
    nodeSelectorValue: ''

